// "use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "styled-components";
import { cn } from "@/lib/utils";
import Header from "@/components/header/header"
import { StoreProvider } from "@/lib/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en" suppressHydrationWarning={true} >
        <body suppressHydrationWarning={true} className={cn(inter.className, "dark")}>
          <main>
            {children}
          </main>
        </body>
      </html >
    </StoreProvider>
  );
}
